Repository acm-ucr/bap-website, pull requests merged in 2024-12, with the labels that each got.

#155 mission shadow responsive and aboutus responsive
  src/app/about/page.tsx
  src/components/about/Aboutus.tsx
  src/components/about/Purpose.tsx
  src/components/home/EventGallery.tsx
  src/components/home/Mission.tsx
  tailwind.config.ts
Labels: responsiveness

#172 Made resource pages responsive for mobile/small screens
  src/app/resources/[section]/page.tsx
Labels: ready to merge

#169 mission and prev board responsive
  src/components/board/DropdownContent.tsx
  src/components/board/PrevBoard.tsx
  src/components/home/Mission.tsx
  src/data/prevBoardData.ts
Labels: board, ready to merge, responsiveness

#150 Fix landing responsiveness
  src/components/Navigation.tsx
  src/components/events/Calendar.tsx
  src/components/home/Landing.tsx
Labels: ready to merge

#166 Made title responsive
  src/components/Navigation.tsx
Labels: ready to merge

#170 calender height change
  src/components/events/Calendar.tsx
Labels: ready to merge
