Repository acm-ucr/bap-website, pull requests merged in 2024-10, with the labels that each got.

#44 add footer
  package-lock.json
  package.json
  src/components/Footer.tsx
Labels: ready for review, ready to merge

#38 Add bootstrap and create navbar
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/Navigation.tsx
  src/data/navData.ts
Labels: ready to merge

#45 Add mission statement
  src/components/home/Mission.tsx
Labels: small changes needed

#54 fix footer
  src/components/Footer.tsx
Labels: ready for review

#39 Aboutus
  src/components/about/Aboutus.tsx
Labels: do not merge

#40 Membership Form Button
  src/app/membership/page.tsx
  src/components/membership/Button.tsx
Labels: ready for review, do not merge

#69 fixed footer pt.2
  src/components/Footer.tsx
Labels: small changes

#76 Added responsive parameters for EventCard.tsx
  src/components/events/EventCard.tsx
Labels: ready for review

#78 add gallery, arrows, and half label
  src/app/page.tsx
  src/components/home/EventGallery.tsx
Labels: question
