Repository acm-ucr/bap-website, pull requests merged in 2024-11, with the labels that each got.

#100 add first board dropdown
  src/app/board/page.tsx
  src/components/board/DropdownContent.tsx
  src/components/board/PrevBoard.tsx
Labels: ready for review, board

#116 add div for footer spacing
  eslint.config.mjs
  src/app/layout.tsx
Labels: Universal, small changes

#130 Fixed paddings and text sizes
  src/app/events/page.tsx
  src/app/membership/page.tsx
  src/app/page.tsx
  src/components/Title.tsx
  src/components/about/Aboutus.tsx
  src/components/about/Purpose.tsx
  src/components/home/EventGallery.tsx
  src/components/home/Mission.tsx
  src/components/membership/MembershipParagraph.tsx
Labels: ready to merge

#132 Added animation to membership
  package-lock.json
  package.json
  src/app/membership/page.tsx
  tailwind.config.ts
Labels: ready to merge

#135 Added animations for about us page
  src/components/about/Aboutus.tsx
  tailwind.config.ts
Labels: ready to merge

#131 Added text and formatted Resource Page
  src/app/resources/[section]/page.tsx
Labels: do not merge

#134 fade right animation purpose icons
  src/components/about/Purpose.tsx
  tailwind.config.ts
Labels: ready to merge

#129 animating landing page box
  src/components/home/Landing.tsx
  tailwind.config.ts
Labels: ready to merge
